import SwiftUI

public extension Image {
  static let bell = Self(systemName: "bell")
  static let booksVertical = Self(systemName: "books.vertical")
  static let calendar = Self(systemName: "calendar")
  static let cameraFill = Self(systemName: "camera.fill")
  static let checkList = Self(systemName: "checklist")
  static let chevronForward = Self(systemName: "chevron.forward")
  static let clock = Self(systemName: "clock")
  static let clockArrowCirclePath = Self(systemName: "clock.arrow.2.circlepath")
  static let checkmark = Self(systemName: "checkmark")
  static let checkmarkCircle = Self(systemName: "checkmark.circle")
  static let checkmarkCircleFill = Self(systemName: "checkmark.circle.fill")
  static let chevronBack = Self(systemName: "chevron.backward")
  static let circle = Self(systemName: "circle")
  static let ellipsisCircle = Self(systemName: "ellipsis.circle")
  static let eye = Self(systemName: "eye")
  static let eyeSlash = Self(systemName: "eye.slash")
  static let exclamationmarkCircleFill = Self(systemName: "exclamationmark.circle.fill")
  static let exclamationmarkTriangleFill = Self(systemName: "exclamationmark.triangle.fill")
  static let infoCircle = Self(systemName: "info.circle")
  static let listDash = Self(systemName: "list.dash")
  static let person = Self(systemName: "person")
  static let photo = Self(systemName: "photo")
  static let plusCircle = Self(systemName: "plus.circle")
  static let `repeat` = Self(systemName: "repeat")
  static let trash = Self(systemName: "trash")
}
